version: "3.8"

services:
  nginx:
    build: ./nginx
    image: nginx
    container_name: "nginx_cont"
    ports:
      - "80:80"
    restart: always
    depends_on:
      - django_app
    networks:
      - notes-app-nw

  django_app:
    build:
      context: .
    image: django_app
    container_name: "django_cont"
    ports:
      - "8000:8000"
    command: sh -c "python manage.py migrate --noinput && gunicorn notesapp.wsgi --bind 0.0.0.0:8000"
    env_file:
      - ".env"
    depends_on:
      - db
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/admin || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - notes-app-nw

  db:
    image: mysql
    container_name: "db_cont"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test_db
    volumes:
      - ./data/mysql/db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    networks:
      - notes-app-nw

networks:
  notes-app-nw:









pipeline {
    agent any 
    
    stages{
        stage("Code"){
            steps{
                 echo "Clonig the code"
                 git url:"https://github.com/Deep2553/django-notes-app.git", branch:"main"
            }
           
        }
        stage("build"){
            steps{
                 echo "Building image"
                 sh "docker build -t django-project ."
            }
        }
        
        stage("Push to Docker Hub"){
            steps{
                 echo "Depoying the container"
                 
                 withCredentials([usernamePassword(credentialsId:"dockerhub", passwordVariable:"dockerhubPass", usernameVariable:"dockerhubUser")]){
                 sh "docker tag django-project ${env.dockerhubUser}/django-project:latest"
                 sh "docker login -u ${env.dockerhubUser} -p ${env.dockerhubPass}"
                 sh "docker push ${env.dockerhubUser}/django-project:latest"
                }
            }
        }
        stage("Deploy"){
            steps{
                 echo "Deploy"
                 sh "docker-compose down && docker-compose up -d"
            }
            
        }
} 
}
